version: '3.4'

services:
  redis:
    image: redis
    restart: always
    volumes:
       - /data:/var/lib/redis


  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DEMO_REDIS_ADDR=redis:6379
      - DEMO_APP_ADDR=localhost:8080
    ports:
    - 8000:8080
    depends_on:
      - redis

