- name: update apt-get
  apt: update_cache=yes
  sudo: yes
  tags:
    - prepare

- name: Set timezone variables
  sudo: yes
  copy: content='Asia/Kolkata'
        dest=/etc/timezone
        owner=root
        group=root
        mode=0644
  notify:
    - update timezone
  tags:
    - prepare

- name: Install required system packages.
  apt: pkg={{ item }} state=installed
  with_items: system_packages
  sudo: yes
  tags:
    - prepare
    - setup

- name: Create a demo user
  user:
    name: demo
    state: present
  tags:
    - prepare
    - setup

- name: Update Hostname
  hostname:
    name="demo-ops"
  tags:
    - prepare
    - setup